package app.anothermorsetrainer.morsekit

// Ham-weighted, frequency-ordered word list for the QRQ word tiers.
// Leads with on-air/QSO vocabulary, then fills with clean general
// high-frequency English. Auto-generated by tools/gen_words.py — do
// not hand-edit; regenerate instead.
//
// Translated from MorseKit/MorseDataWords.swift. Swift attaches this to
// MorseData via an extension; Kotlin objects can't be split across files,
// so it lives here as an internal top-level val and MorseData re-exposes it.

/** 500 words, most useful first, for the Top N word tiers. */
internal val rankedWordsData: List<String> = listOf(
    "CQ", "DE", "RST", "RIG", "ANT", "PWR", "WX", "QTH", "NAME", "AGE",
    "CALL", "SIG", "FB", "HR", "HW", "ES", "GA", "GE", "GM", "GN",
    "TU", "TNX", "PSE", "UR", "VY", "WID", "AGN", "ABT", "BK", "CFM",
    "CUL", "DX", "FER", "GUD", "NR", "OB", "OM", "OP", "RPT", "SED",
    "SKED", "SRI", "TFC", "WKD", "WL", "YL", "XYL", "73", "88", "DIPOLE",
    "BEAM", "WIRE", "VERT", "LOOP", "WATT", "WATTS", "COAX", "TUNER", "KEY", "PADDLE",
    "BUG", "RADIO", "BAND", "FREQ", "CONTEST", "POTA", "SOTA", "FIELD", "DAY", "PARK",
    "SUMMIT", "GRID", "SECTION", "SERIAL", "NUMBER", "CHECK", "CLASS", "ZONE", "STATE", "PROV",
    "COUNTY", "CITY", "TOWN", "RAIN", "SNOW", "SUN", "CLOUD", "WARM", "COLD", "HOT",
    "COOL", "WIND", "FOG", "CLEAR", "NICE", "FINE", "SOLID", "COPY", "OVER", "ROGER",
    "BREAK", "STBY", "QRL", "QRM", "QRN", "QRO", "QRP", "QRQ", "QRS", "QRT",
    "QRU", "QRV", "QRX", "QRZ", "QSB", "QSL", "QSO", "QSY", "ANTENNA", "POWER",
    "WEATHER", "SIGNAL", "REPORT", "LOCATION", "WORKED", "THANKS", "PLEASE", "AGAIN", "HOPE", "SEND",
    "OLD", "MAN", "LADY", "HAM", "CW", "MORSE", "CODE", "THE", "OF", "AND",
    "TO", "A", "IN", "FOR", "IS", "ON", "THAT", "BY", "THIS", "WITH",
    "I", "YOU", "IT", "NOT", "OR", "BE", "ARE", "FROM", "AT", "AS",
    "YOUR", "ALL", "HAVE", "NEW", "MORE", "AN", "WAS", "WE", "WILL", "HOME",
    "CAN", "US", "ABOUT", "IF", "PAGE", "MY", "HAS", "SEARCH", "FREE", "BUT",
    "OUR", "ONE", "OTHER", "DO", "NO", "INFORMATION", "TIME", "THEY", "SITE", "HE",
    "UP", "MAY", "WHAT", "WHICH", "THEIR", "NEWS", "OUT", "USE", "ANY", "THERE",
    "SEE", "ONLY", "SO", "HIS", "WHEN", "CONTACT", "HERE", "BUSINESS", "WHO", "WEB",
    "ALSO", "NOW", "HELP", "GET", "PM", "VIEW", "ONLINE", "C", "E", "FIRST",
    "AM", "BEEN", "WOULD", "HOW", "WERE", "ME", "S", "SERVICES", "SOME", "THESE",
    "CLICK", "ITS", "LIKE", "SERVICE", "X", "THAN", "FIND", "PRICE", "DATE", "BACK",
    "TOP", "PEOPLE", "HAD", "LIST", "JUST", "YEAR", "INTO", "EMAIL", "TWO", "HEALTH",
    "N", "WORLD", "RE", "NEXT", "USED", "GO", "B", "WORK", "LAST", "MOST",
    "PRODUCTS", "MUSIC", "BUY", "DATA", "MAKE", "THEM", "SHOULD", "PRODUCT", "SYSTEM", "POST",
    "HER", "T", "ADD", "POLICY", "SUCH", "AVAILABLE", "COPYRIGHT", "SUPPORT", "MESSAGE", "AFTER",
    "BEST", "SOFTWARE", "THEN", "JAN", "GOOD", "VIDEO", "WELL", "D", "WHERE", "INFO",
    "RIGHTS", "PUBLIC", "BOOKS", "HIGH", "SCHOOL", "THROUGH", "M", "EACH", "LINKS", "SHE",
    "REVIEW", "YEARS", "ORDER", "VERY", "PRIVACY", "BOOK", "ITEMS", "COMPANY", "R", "READ",
    "GROUP", "NEED", "MANY", "USER", "SAID", "DOES", "SET", "UNDER", "GENERAL", "RESEARCH",
    "UNIVERSITY", "JANUARY", "MAIL", "FULL", "MAP", "REVIEWS", "PROGRAM", "LIFE", "KNOW", "GAMES",
    "WAY", "DAYS", "MANAGEMENT", "P", "PART", "COULD", "GREAT", "UNITED", "HOTEL", "REAL",
    "F", "ITEM", "CENTER", "EBAY", "MUST", "STORE", "TRAVEL", "COMMENTS", "MADE", "DEVELOPMENT",
    "OFF", "MEMBER", "DETAILS", "LINE", "TERMS", "BEFORE", "HOTELS", "DID", "RIGHT", "TYPE",
    "BECAUSE", "LOCAL", "THOSE", "USING", "RESULTS", "OFFICE", "EDUCATION", "NATIONAL", "CAR", "DESIGN",
    "TAKE", "POSTED", "INTERNET", "ADDRESS", "COMMUNITY", "WITHIN", "STATES", "AREA", "WANT", "PHONE",
    "DVD", "SHIPPING", "RESERVED", "SUBJECT", "BETWEEN", "FORUM", "FAMILY", "L", "LONG", "BASED",
    "W", "SHOW", "O", "EVEN", "BLACK", "SPECIAL", "PRICES", "WEBSITE", "INDEX", "BEING",
    "WOMEN", "MUCH", "SIGN", "FILE", "LINK", "OPEN", "TODAY", "TECHNOLOGY", "SOUTH", "CASE",
    "PROJECT", "SAME", "PAGES", "UK", "VERSION", "OWN", "FOUND", "SPORTS", "HOUSE", "RELATED",
    "SECURITY", "BOTH", "G", "AMERICAN", "PHOTO", "GAME", "MEMBERS", "WHILE", "CARE", "NETWORK",
    "DOWN", "COMPUTER", "SYSTEMS", "THREE", "TOTAL", "PLACE", "END", "FOLLOWING", "DOWNLOAD", "H",
    "HIM", "WITHOUT", "PER", "ACCESS", "THINK", "NORTH", "RESOURCES", "CURRENT", "POSTS", "BIG",
    "MEDIA", "LAW", "CONTROL", "WATER", "HISTORY", "PICTURES", "SIZE", "ART", "PERSONAL", "SINCE",
    "INCLUDING", "GUIDE", "SHOP", "DIRECTORY", "BOARD", "CHANGE", "WHITE", "TEXT", "SMALL", "RATING",
    "RATE", "GOVERNMENT", "CHILDREN", "DURING", "USA", "RETURN", "STUDENTS", "V", "SHOPPING", "ACCOUNT",
    "TIMES", "SITES", "LEVEL", "DIGITAL", "PROFILE", "PREVIOUS", "FORM", "EVENTS", "LOVE", "JOHN",
    "MAIN", "HOURS", "IMAGE", "DEPARTMENT", "TITLE", "DESCRIPTION", "NON", "K", "Y", "INSURANCE"
)
